CREATE TABLE IF NOT EXISTS FRED_DATA_RAW (
    SERIES_ID VARCHAR(100),
    OBSERVATION_DATE DATE,
    VALUE FLOAT,
    TITLE VARCHAR,
    FREQUENCY VARCHAR(100),
    UNITS VARCHAR(100),
    EXTRACTED_AT TIMESTAMP_TZ,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_TZ
);

CREATE OR REPLACE TEMPORARY STAGE fred_s3_stage
    URL = {{SQLSTR:S3_URI}}
    CREDENTIALS = (
        AWS_KEY_ID = {{SQLSTR:AWS_ACCESS_KEY_ID}}
        AWS_SECRET_KEY = {{SQLSTR:AWS_SECRET_ACCESS_KEY}}
        AWS_TOKEN = {{SQLSTR:AWS_SESSION_TOKEN}}
    )
    FILE_FORMAT = (
        TYPE = CSV
        SKIP_HEADER = 1
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    );

COPY INTO FRED_DATA_RAW (
    SERIES_ID,
    OBSERVATION_DATE,
    VALUE,
    TITLE,
    FREQUENCY,
    UNITS,
    EXTRACTED_AT,
    SOURCE_FILE,
    LOADED_AT
)
FROM (
    SELECT
        t.$1::VARCHAR,
        TRY_TO_DATE(t.$2),
        TRY_TO_DOUBLE(t.$3),
        t.$4::VARCHAR,
        t.$5::VARCHAR,
        t.$6::VARCHAR,
        TRY_TO_TIMESTAMP_TZ(t.$7),
        METADATA$FILENAME::VARCHAR,
        CURRENT_TIMESTAMP()
    FROM @fred_s3_stage t
)
ON_ERROR = 'CONTINUE'
FORCE = FALSE;
