CREATE TABLE IF NOT EXISTS FRED_DATA_CURATED (
    SERIES_ID VARCHAR(100),
    OBSERVATION_DATE DATE,
    VALUE FLOAT,
    TITLE VARCHAR,
    FREQUENCY VARCHAR(100),
    UNITS VARCHAR(100),
    EXTRACTED_AT TIMESTAMP_TZ,
    SOURCE_FILE VARCHAR,
    LOADED_AT TIMESTAMP_TZ,
    UPDATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO FRED_DATA_CURATED target
USING (
    SELECT
        SERIES_ID,
        OBSERVATION_DATE,
        VALUE,
        TITLE,
        FREQUENCY,
        UNITS,
        EXTRACTED_AT,
        SOURCE_FILE,
        LOADED_AT
    FROM FRED_DATA_RAW
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY SERIES_ID, OBSERVATION_DATE
        ORDER BY EXTRACTED_AT DESC NULLS LAST, LOADED_AT DESC NULLS LAST
    ) = 1
) source
ON target.SERIES_ID = source.SERIES_ID
AND target.OBSERVATION_DATE = source.OBSERVATION_DATE
WHEN MATCHED THEN UPDATE SET
    VALUE = source.VALUE,
    TITLE = source.TITLE,
    FREQUENCY = source.FREQUENCY,
    UNITS = source.UNITS,
    EXTRACTED_AT = source.EXTRACTED_AT,
    SOURCE_FILE = source.SOURCE_FILE,
    LOADED_AT = source.LOADED_AT,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (
    SERIES_ID,
    OBSERVATION_DATE,
    VALUE,
    TITLE,
    FREQUENCY,
    UNITS,
    EXTRACTED_AT,
    SOURCE_FILE,
    LOADED_AT,
    UPDATED_AT
) VALUES (
    source.SERIES_ID,
    source.OBSERVATION_DATE,
    source.VALUE,
    source.TITLE,
    source.FREQUENCY,
    source.UNITS,
    source.EXTRACTED_AT,
    source.SOURCE_FILE,
    source.LOADED_AT,
    CURRENT_TIMESTAMP()
);
